name: template
description: This is a template project.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ">=2.14.0 <=3.7.11"

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.2.0
  get_cli: ^1.8.1
  audioplayers: ^3.0.0
  get_storage: 2.1.1
  path: ^1.8.3
  flutter_markdown: 0.6.14
  wheel:
    git:
      url: https://github.com/RedDwarfTech/wheel.git
      ref: main

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/cfg/
    - assets/law/

flutter_intl:
  enabled: true

dependency_overrides:
